// belong: 0 不属于我 1 属于我
// type :  0 放地上 1 放墙上
goods = [
    [
        {
            id: 1,
            name: "S型躺椅",
            des: "人生就像咸鱼，爱躺才会赢",
            width: 2.3,
            height: 2.1,
            belong: 1,
            type: 0,
            src: '1/1.png'
        },
        {
            id: 2,
            name: "豪华双人床",
            des: "床有多大，心就有多大",
            width: 2.75,
            height: 2.75,
            belong: 1,
            type: 0,
            src: '1/5.png'
        }, {
        id: 3,
        name: "奶茶色双人床",
        des: "人是铁，床是吸铁石",
        width: 3.3,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '1/2.png'
    }, {
        id: 4,
        name: "老式储物柜",
        des: "柜子一开，小时候的回忆就涌出来",
        width: 3.8,
        height: 4.5,
        belong: 1,
        type: 0,
        src: '1/6.png'
    }, {
        id: 5,
        name: "老式储物柜",
        des: "柜子一开，小时候的回忆就涌出来",
        width: 3.8,
        height: 4.5,
        belong: 1,
        type: 0,
        src: '1/6.png'
    }, {
        id: 6,
        name: "很有架子",
        des: "每天都摆架子给我看",
        width: 3.85,
        height: 4.5,
        belong: 1,
        type: 0,
        src: '1/9.png'
    }, {
        id: 7,
        name: "故事酒柜",
        des: "心中有故事，哪瓶都是拉菲",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/14.png'
    }, {
        id: 8,
        name: "小角柜",
        des: "小资从小角柜开始",
        width: 3.85,
        height: 3.8,
        belong: 1,
        type: 0,
        src: '1/37.png'
    }, {
        id: 9,
        name: "简易书架",
        des: "没有书架的家，是没有灵魂的",
        width: 3.8,
        height: 4.5,
        belong: 1,
        type: 0,
        src: '1/7.png'
    }, {
        id: 10,
        name: "焦糖衣柜",
        des: "衣柜衣柜 谁是，世界上最漂亮的女人",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/87.png'
    }, {
        id: 11,
        name: "北欧衣柜",
        des: "玩个魔术，来个大变仙女",
        width: 3.85,
        height: 4.5,
        belong: 1,
        type: 0,
        src: '1/10.png'
    }, {
        id: 12,
        name: "迷你茶几",
        des: "一个茶几 一本书，我能睡它一下午",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/56.png'
    }, {
        id: 13,
        name: "古董边柜",
        des: "再过500年，它就是个古董",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/63.png'
    }, {
        id: 14,
        name: "深色茶几",
        des: "可别学它，上面满满是杯具",
        width: 3.85,
        height: 4.5,
        belong: 1,
        type: 0,
        src: '1/70.png'
    }, {
        id: 15,
        name: "白色餐桌",
        des: "有了它，就有了精致的生活",
        width: 3.85,
        height: 3.4,
        belong: 1,
        type: 0,
        src: '1/23.png'
    }, {
        id: 16,
        name: "黄色电视柜",
        des: "一直和电视争宠，但从未赢过",
        width: 3.85,
        height: 3.2,
        belong: 1,
        type: 0,
        src: '1/17.png'
    }, {
        id: 17,
        name: "淡白茶几",
        des: "谁说实用和颜值不能兼具",
        width: 3.85,
        height: 3.6,
        belong: 1,
        type: 0,
        src: '1/24.png'
    }, {
        id: 18,
        name: "小板凳",
        des: "坐下就是全家福，少一个都不行",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/74.png'
    }, {
        id: 19,
        name: "木质摇椅",
        des: "摇啊摇，摇到外婆桥",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/79.png'
    }, {
        id: 20,
        name: "皮质单人椅",
        des: "舒服得像男友的拥抱",
        width: 3.25,
        height: 3.2,
        belong: 1,
        type: 0,
        src: '1/39.png'
    }, {
        id: 21,
        name: "日式柔软靠椅",
        des: "陷下去的那一刻，心都化了",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/41.png'
    }, {
        id: 22,
        name: "化妆台",
        des: "清晨看一眼，精神一整天",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/80.png'
    }, {
        id: 23,
        name: "挂壁置物架",
        des: "收藏生活的小美好",
        width: 3.85,
        height: 4.55,
        belong: 1,
        type: 0,
        src: '1/82.png'
    }, {
        id: 24,
        name: "木质鞋柜",
        des: "最有味道的家具",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/83.png'
    }, {
        id: 25,
        name: "床头柜",
        des: "我有许多秘密，就不告诉你",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/84.png'
    }, {
        id: 26,
        name: "方型矮柜",
        des: "家具里的小短腿",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/85.png'
    }, {
        id: 27,
        name: "三角梳妆台",
        des: "魔镜魔镜 我是不是，这条gai上最靓的仔",
        width: 3.85,
        height: 3.85,
        belong: 1,
        type: 0,
        src: '1/86.png'
    }, {
        id: 28,
        name: "双人躺椅",
        des: "和已知的人，躺赢未知的人生",
        width: 3.85,
        height: 3.2,
        belong: 1,
        type: 0,
        src: '1/18.png'
    }, {
        id: 29,
        name: "深色沙发",
        des: "无沙发不成家",
        width: 3.85,
        height: 3.8,
        belong: 1,
        type: 0,
        src: '1/32.png'
    }, {
        id: 30,
        name: "豪华L型沙发",
        des: "好的沙发，才能让你发",
        width: 3.85,
        height: 4.5,
        belong: 1,
        type: 0,
        src: '1/8.png'
    }, {
        id: 31,
        name: "几何沙发",
        des: "围着坐才更有温度",
        width: 3.85,
        height: 4.5,
        belong: 1,
        type: 0,
        src: '1/15.png'
    }, {
        id: 32,
        name: "黄色皮沙发",
        des: "我在客厅里，安了个王座",
        width: 3.85,
        height: 3.8,
        belong: 1,
        type: 0,
        src: '1/36.png'
    }, {
        id: 33,
        name: "黄色皮质沙发椅",
        des: "裹紧小毛毯，陷进沙发里",
        width: 3.85,
        height: 3.2,
        belong: 1,
        type: 0,
        src: '1/11.png'
    },
    ]
    ,
    [
        {
            id: 34,
            name: "粉红音箱",
            des: "良好邻里关系的障碍",
            width: 2.8,
            height: 2.8,
            belong: 1,
            type: 0,
            src: '2/60.png'
        }, {
        id: 35,
        name: "粉红音箱",
        des: "良好邻里关系的障碍",
        width: 2.3,
        height: 2.3,
        belong: 1,
        type: 0,
        src: '2/61.png'
    }, {
        id: 36,
        name: "柱型台灯",
        des: "打开开关，让心更明亮一些",
        width: 2.3,
        height: 2.3,
        belong: 1,
        type: 0,
        src: '2/71.png'
    }, {
        id: 37,
        name: "方型台灯",
        des: "打开开关，让心更明亮一些",
        width: 2.3,
        height: 2.3,
        belong: 1,
        type: 0,
        src: '2/77.png'
    }, {
        id: 38,
        name: "中式落地灯柱",
        des: "生活需要情调，气氛需要营造",
        width: 2.6,
        height: 3.8,
        belong: 1,
        type: 0,
        src: '2/76.png'
    }, {
        id: 39,
        name: "球形落地灯",
        des: "谁还不是个掌上明珠呢",
        width: 0.8,
        height: 1.0,
        belong: 1,
        type: 0,
        src: '2/29.png'
    }, {
        id: 40,
        name: "阿拉伯数字时钟",
        des: "如果，时间能倒着走就好了",
        width: 0.8,
        height: 0.8,
        belong: 1,
        type: 1,
        src: '2/31.png'
    }, {
        id: 41,
        name: "白色空调",
        des: "燥热的心情，有时候需要冷静冷静",
        width: 1.6,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '2/21.png'
    }, {
        id: 42,
        name: "白色微波炉",
        des: "叮一下，开启热气腾腾的生活",
        width: 2.8,
        height: 2.6,
        belong: 1,
        type: 0,
        src: '2/45.png'
    }, {
        id: 43,
        name: "黑色烤炉",
        des: "烘焙的味道，治愈的味道",
        width: 2.8,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '2/78.png'
    }, {
        id: 44,
        name: "黑曜石冰箱",
        des: "把冰箱塞满，才是生活",
        width: 3.4,
        height: 3.4,
        belong: 1,
        type: 0,
        src: '2/79.png'
    }, {
        id: 45,
        name: "黑曜石冰箱",
        des: "把冰箱塞满，才是生活",
        width: 2.85,
        height: 3.15,
        belong: 1,
        type: 1,
        src: '2/33.png'
    },
    ],
    [
        {
            id: 46,
            name: "洗碗池",
            des: "一个好看的洗碗池，让你爱上洗碗",
            width: 3.2,
            height: 3.4,
            belong: 1,
            type: 0,
            src: '3/16.png'
        }, {
        id: 47,
        name: "经典浴缸",
        des: "在这里，你才可以随心所浴",
        width: 3.2,
        height: 3.0,
        belong: 1,
        type: 0,
        src: '3/16.png'
    }, {
        id: 48,
        name: "淋浴间",
        des: "浴室好声音，非你莫属",
        width: 2.8,
        height: 3.25,
        belong: 1,
        type: 0,
        src: '3/13.png'
    }, {
        id: 49,
        name: "全身镜",
        des: "里面住着个小仙女",
        width: 3.2,
        height: 3.0,
        belong: 1,
        type: 0,
        src: '3/26.png'
    },
    ],
    [
        {
            id: 50,
            name: "跑步机",
            des: "打个赌吧，你一年能跑几次",
            width: 2.8,
            height: 2.8,
            belong: 1,
            type: 0,
            src: '4/40.png'
        }, {
        id: 51,
        name: "深色帐篷",
        des: "心中有沙滩，哪里都能露营",
        width: 2.8,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '4/19.png'
    }, {
        id: 52,
        name: "彩色气球",
        des: "人生就要飘一点",
        width: 2.8,
        height: 3.8,
        belong: 1,
        type: 0,
        src: '4/51.png'
    }, {
        id: 53,
        name: "宠物猫",
        des: "家里真正的主人",
        width: 2.6,
        height: 2.6,
        belong: 1,
        type: 0,
        src: '4/52.png'
    }, {
        id: 53,
        name: "小黄鸭",
        des: "你的泡澡伴侣",
        width: 2.3,
        height: 2.3,
        belong: 1,
        type: 0,
        src: '4/53.png'
    }, {
        id: 54,
        name: "猫窝",
        des: "你的泡澡伴侣",
        width: 2.8,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '4/55.png'
    }, {
        id: 55,
        name: "武士刀架",
        des: "别惹我，当心我削你",
        width: 2.8,
        height: 2.6,
        belong: 1,
        type: 0,
        src: '4/64.png'
    }, {
        id: 57,
        name: "挂扇",
        des: "天生擅长煽风点火",
        width: 2.6,
        height: 2.6,
        belong: 1,
        type: 1,
        src: '4/65.png'
    }, {
        id: 58,
        name: "唯美花瓶",
        des: "每天来点新“花”样",
        width: 2.6,
        height: 2.6,
        belong: 1,
        type: 1,
        src: '4/67.png'
    }, {
        id: 59,
        name: "唯美花瓶",
        des: "每天来点新“花”样",
        width: 2.6,
        height: 2.6,
        belong: 1,
        type: 1,
        src: '4/68.png'
    }, {
        id: 60,
        name: "老式电视",
        des: "时光是记忆的橡皮擦",
        width: 2.8,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '4/69.png'
    }, {
        id: 61,
        name: "小坐垫",
        des: "坐下那一刻，生活才刚刚开始",
        width: 2.8,
        height: 2.6,
        belong: 1,
        type: 0,
        src: '4/80.png'
    }, {
        id: 62,
        name: "碧空游戏机",
        des: "上上下下，左右左右",
        width: 2.6,
        height: 3.8,
        belong: 1,
        type: 0,
        src: '4/20.png'
    }, {
        id: 63,
        name: "不规律几何地毯",
        des: "我的人生就像，这张地毯一样不规律",
        width: 2.8,
        height: 2.6,
        belong: 1,
        type: 0,
        src: '4/4.png'
    }, {
        id: 64,
        name: "跳舞毯",
        des: "谈恋爱不如跳舞",
        width: 2.8,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '4/42.png'
    }, {
        id: 65,
        name: "海德钢琴",
        des: "坐下来，和灵魂“弹一弹”",
        width: 2.8,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '4/22.png'
    }, {
        id: 66,
        name: "黄色弹力球",
        des: "从弹珠到弹力球是，生活的尺度",
        width: 2.8,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '4/44.png'
    }, {
        id: 67,
        name: "立式拳击沙袋",
        des: "假想男友，怎么都打不够",
        width: 2.8,
        height: 3.7,
        belong: 1,
        type: 0,
        src: '4/27.png'
    }, {
        id: 68,
        name: "猫爬架",
        des: "主子不无聊，我也就开心了",
        width: 2.8,
        height: 3.0,
        belong: 1,
        type: 0,
        src: '4/54.png'
    }, {
        id: 69,
        name: "球形木椅",
        des: "主子不无聊，我也就开心了",
        width: 2.8,
        height: 3.7,
        belong: 1,
        type: 0,
        src: '4/26.png'
    }, {
        id: 70,
        name: "玩偶兔",
        des: "成长路上的倾听者，少时梦想的保护伞",
        width: 2.8,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '4/43.png'
    }, {
        id: 71,
        name: "玩偶兔",
        des: "成长路上的倾听者，少时梦想的保护伞",
        width: 2.8,
        height: 2.8,
        belong: 1,
        type: 0,
        src: '4/58.png'
    },
    ]
];